default: &default
  time_zone: 'Paris'
  secret_key_base: 56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4
  facebook_key: "165439534138171"
  facebook_secret: "ff312e02ae2a031c3d5218711e6071ed"
  rollbar_server_token: '3b0dbe3a4af946e1aee11934b2768453'

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true


staging:
  secret_key_base: <%= ENV["CDJ_AUDE_SECRET_KEY_BASE"] %>
  server_name: <%= ENV["CDJ_AUDE_SERVER_NAME"] %>
  rollbar_server_token: <%= ENV["CDJ_AUDE_ROLLBAR_SERVER_TOKEN"] %>
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: <%= ENV["CDJ_AUDE_TWITTER_KEY"] %>
  twitter_secret: <%= ENV["CDJ_AUDE_TWITTER_SECRET"] %>
  facebook_key: <%= ENV["CDJ_AUDE_FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["CDJ_AUDE_FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["CDJ_AUDE_GOOGLE_OAUTH2_KEY"] %>
  google_oauth2_secret: <%= ENV["CDJ_AUDE_GOOGLE_OAUTH2_SECRET"] %>
  smtp_username: <%= ENV["CDJ_AUDE_SMTP_USERNAME"] %>
  smtp_password: <%= ENV["CDJ_AUDE_SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["CDJ_AUDE_SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["CDJ_AUDE_SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["CDJ_AUDE_SMTP_PORT"] %>
  smtp_starttls_auto: <%= ENV["CDJ_AUDE_SMTP_STARTTLS_AUTO"] %>
  smtp_authentication: <%= ENV["CDJ_AUDE_SMTP_AUTHENTICATION"] %>
  <<: *maps
  <<: *apis

